import pytest
from unittest.mock import MagicMock, patch
from rdkit import Chem
from moleditpy.ui.io_logic import IOManager

class MockMainWindow(IOManager):
    def __init__(self, host=None):
        self._host = host or MagicMock()
        IOManager.__init__(self, self._host)
        
        # Managers if host is fresh MagicMock
        if not hasattr(self._host, "state_manager"):
            self._host.state_manager = MagicMock()
        if not hasattr(self._host, "init_manager"):
            self._host.init_manager = MagicMock()
        if not hasattr(self._host, "view_3d_manager"):
            self._host.view_3d_manager = MagicMock()

        self._host.view_3d_manager.current_mol = None
        self._host.settings = {}  # Prevent truthy MagicMock from bypassing chemistry checks
        self._statusBar = MagicMock()
        self._host.statusBar.return_value = self._statusBar

    def __getattr__(self, name):
        return getattr(self._host, name)

    @property
    def data(self): return self.host.state_manager.data
    @property
    def scene(self): return self.host.init_manager.scene
    @property
    def settings(self): return self.host.init_manager.settings
    @property
    def view_2d(self): return self.host.init_manager.view_2d
    @property
    def plotter(self): return self.host.view_3d_manager.plotter

    @property
    def current_mol(self): return self.host.view_3d_manager.current_mol
    @current_mol.setter
    def current_mol(self, v): self.host.view_3d_manager.current_mol = v

    @property
    def current_file_path(self): return getattr(self._host, "current_file_path", None)
    @current_file_path.setter
    def current_file_path(self, v): self._host.current_file_path = v

    def statusBar(self):
        return self._statusBar

    def check_unsaved_changes(self):
        return True

def test_set_mol_prop_safe_robustness():
    """Test that _set_mol_prop handles RDKit exceptions by narrowing."""
    from moleditpy.ui.io_logic import _set_mol_prop_safe
    mol = Chem.MolFromSmiles("C")
    # This should not raise even if an invalid value is passed (it's suppressed)
    _set_mol_prop_safe(mol, "test_prop", "not_an_int")
    assert not mol.HasProp("test_prop")

def test_get_set_mol_prop_instance():
    """Test instance versions of prop helpers."""
    win = MockMainWindow()
    mol = Chem.MolFromSmiles("C")
    
    # Valid int
    win._set_mol_prop(mol, "int_prop", 123)
    assert win._get_mol_prop(mol, "int_prop") == 123
    
    # Valid float
    win._set_mol_prop(mol, "float_prop", 1.23)
    assert pytest.approx(win._get_mol_prop(mol, "float_prop")) == 1.23
    
    # Fallback to string
    win._set_mol_prop(mol, "str_prop", "hello")
    assert win._get_mol_prop(mol, "str_prop") == "hello"

def test_save_as_xyz_no_mol():
    """Test save_as_xyz handles missing molecule gracefully."""
    win = MockMainWindow()
    win.save_as_xyz()
    win.statusBar().showMessage.assert_called_with("Error: Please generate a 3D structure first.")

def test_save_as_xyz_logic(tmp_path):
    """Test the core logic of save_as_xyz (mocking the file dialog)."""
    win = MockMainWindow()
    mol = Chem.MolFromSmiles("C")
    from rdkit.Chem import AllChem
    AllChem.EmbedMolecule(mol)
    win.current_mol = mol
    
    save_path = str(tmp_path / "test.xyz")
    with patch("PyQt6.QtWidgets.QFileDialog.getSaveFileName", return_value=(save_path, "XYZ")):
        win.save_as_xyz()
        
    import os
    assert os.path.exists(save_path)
    with open(save_path, "r") as f:
        content = f.read()
        assert "1" in content # atom count
        assert "Generated by MoleditPy" in content

def test_load_mol_counts_fix():
    """Test that the MOL counts line fixer is robust."""
    win = MockMainWindow()
    # No V2000/V3000
    line = "  1  0  0  0  0  0  0  0  0  0  1"
    fixed = win.fix_mol_counts_line(line)
    assert "V2000" in fixed
    assert len(fixed) == 39
    
    # Already V2000
    line_v2 = "  1  0  0  0  0  0  0  0  0  0  1 V2000"
    assert win.fix_mol_counts_line(line_v2) == line_v2

@pytest.mark.parametrize("invalid_xyz", [
    "1\nTitle\n", # Missing atom line
    "1\nTitle\nX 0 0 0", # Invalid element
    "0\nTitle\n", # Zero atoms
])
def test_load_xyz_robustness(invalid_xyz, tmp_path):
    """Test that XYZ parser handles malformed files via statusBar."""
    win = MockMainWindow()
    xyz_file = tmp_path / "bad.xyz"
    xyz_file.write_text(invalid_xyz)
    
    win.load_xyz_file(str(xyz_file))
        
    # Should have shown an error in statusBar
    win.statusBar().showMessage.assert_called()
    args, _ = win.statusBar().showMessage.call_args
    assert "Error parsing XYZ file" in args[0]
